name: Branch Merging Pipeline

concurrency:
  group: merge-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "Asif_Branch"
      - "Pavan_Branch"
      - "Shiva_Branch"

jobs:
  merge-to-Staging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Selective Merge to Staging
        run: |
          git checkout Staging
          git pull origin Staging

          # Merge specific directories based on source branch
          case "${{ github.ref_name }}" in
            "Asif_Branch") git checkout ${{ github.ref_name }} -- backend/ ;;
            "Pavan_Branch") git checkout ${{ github.ref_name }} -- frontend/ ;;
            "Shiva_Branch") git checkout ${{ github.ref_name }} -- frontend/ ;;
          esac

          git add .
          git commit -m "Auto-merge: ${{ github.ref_name }} → Staging" || echo "No changes to commit"
          git push origin Staging

  build-and-Test:
    needs: merge-to-Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: Staging

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Frontend CI
        working-directory: Frontend
        run: |
          # npm ci
          # npm run build
          # npm Test

      - name: Backend CI
        working-directory: backend
        run: |
          # npm ci
          # npm Test
          # npm run lint

  merge-to-Test:
    needs: build-and-Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Staging to Test
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout Test
          git merge Staging --no-ff -m "Auto-merge: Staging → Test"
          git push origin Test
